apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    io.kompose.service: grafana
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30300  
  selector:
    io.kompose.service: grafana
