apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    io.kompose.service: prometheus
spec:
  type: NodePort
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
      nodePort: 30900  
  selector:
    io.kompose.service: prometheus
