apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    io.kompose.service: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  template:
    metadata:
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
              subPath: prometheus.yml
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
