apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  # base64: admin -> YWRtaW4=, promgrafana2024 -> cHJvbWdyYWZhbmEyMDI0
  admin_user: YWRtaW4=
  admin_password: cHJvbWdyYWZhbmEyMDI0
